### ISSUE TITLE
mailchimp sign up

### ISSUE THREAD

**Issue by charlottesales** [kentcc/kelsi#65] opened 2015-03-16 09:34 UTC
Hi Lidor, 

We have changed the mailchimp account that the ebulletin will be sent from. I assume this means the sign up box needs changing?

Also I have embedded a sign up on asset ID 23528 in the content, which looks OK but isn't working properly, so could you take a look at this as part of it please. 

I'll email you the log in details separately. 

Thanks

**Comment by LidorLapid** [comment] 2015-03-16 09:56
I've changed the sign-up box so it now points to the new list.

Regarding asset ID 23528,  the issue is that the WYSIWYG editor processed out some of the markup required for the form to work (i.e. the form tag). I'd recommend splitting the content into two WYSIWYG containers and a Raw HTML container in-between them for the form code. 

We'll also need to do a bit of work to make the button display in a way that's consistent with the rest of the site. As a starting point I'd suggest removing the following two lines from the snippet:

<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

**Comment by LidorLapid** [comment] 2015-03-16 09:58
Looks like GitHub unhelpfully removed the markup I copied from the snippet! I meant that the link and style tags should be removed.

**Comment by charlottesales** [comment] 2015-03-16 10:11
Hi Lidor,

I have split it out as suggested but not sure which part to delete? I always end up messing it up, can you take a look and remove the right part please ☺

**Comment by LidorLapid** [comment] 2015-03-16 10:29
Done. :)

**Closed by LidorLapid** 2015-03-16 10:29 UTC
